# Generated by .github/scripts/render-homebrew-formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/core-editor/ore"
  version "0.146.4"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.4/codex-package-aarch64-apple-darwin.tar.gz"
      sha256 "ffdb7407a4a53a04275a936f0d1c55c74ee4c044c2c028626b80af7606d79396"
    end
    on_intel do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.4/codex-package-x86_64-apple-darwin.tar.gz"
      sha256 "4ad6c818c5089d9e77b69d0c5147e94d38c376eff274a0cb0b7b274ac261a7d1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.4/codex-package-aarch64-unknown-linux-musl.tar.gz"
      sha256 "3826399edf61910b3f76a563c77086dd51a5757306e0e05f9b8a38cce1b4c98f"
    end
    on_intel do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.4/codex-package-x86_64-unknown-linux-musl.tar.gz"
      sha256 "d50cde61cac04415fc05af26b8587a137a2c98dc8fecf17efb3511ce980a67e3"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ore --version")
  end
end
