# Generated by .github/scripts/render-homebrew-formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/core-editor/ore"
  version "0.146.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.0/codex-package-aarch64-apple-darwin.tar.gz"
      sha256 "088a8401f0e321e13c5a203ce3bb839c3ccad08ddb66632f11dca5e2bd068bee"
    end
    on_intel do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.0/codex-package-x86_64-apple-darwin.tar.gz"
      sha256 "2196efcfa763fa5d9448b1d587a7a56201537a6dbfbfff0a7f77dd2be28ed197"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.0/codex-package-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4b171242ad653535eaef1112593b350aeef50b570b850138972a5af5e1121e28"
    end
    on_intel do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.0/codex-package-x86_64-unknown-linux-musl.tar.gz"
      sha256 "06060bfd564cbea0eadff90e6f3e4157516fc175f7198ef039998eb4b3638722"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s.sub(/-ore\.\d+$/, ""), shell_output("#{bin}/ore --version")
  end
end
