# Generated by .github/scripts/render-homebrew-formula.sh. Do not edit by hand.
class Ore < Formula
  desc "Coding agent for the terminal"
  homepage "https://github.com/core-editor/ore"
  version "0.146.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.2/codex-package-aarch64-apple-darwin.tar.gz"
      sha256 "dc3e30756b6d5a88bbf881ea0b1408a04bf829b698f3f6e984af99c497ce7c6f"
    end
    on_intel do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.2/codex-package-x86_64-apple-darwin.tar.gz"
      sha256 "0b2454697400bc012fa880a763b4f4e1b50fc7372ab938d1e1546fa2c594b915"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.2/codex-package-aarch64-unknown-linux-musl.tar.gz"
      sha256 "36cdb3ef4de9fdffba770dc0ef5d3d90ca14bedc767ed703e1003a5b4c13639e"
    end
    on_intel do
      url "https://github.com/core-editor/ore/releases/download/ore-v0.146.2/codex-package-x86_64-unknown-linux-musl.tar.gz"
      sha256 "4aae075c3148aaf47855d5d89e3597544596e3660d433cc1948dd62174506978"
    end
  end

  def install
    # ore resolves its siblings relative to itself; keep the bundle assembled.
    libexec.install Pathname.glob("{*,.[!.]*}")
    bin.install_symlink libexec/"bin/ore"
    generate_completions_from_executable(libexec/"bin/ore", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ore --version")
  end
end
